# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [4]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [5]:
from google.colab import files
uploaded = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [6]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("applicants_data.csv")

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [8]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN", "NAME"])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [9]:
# Create a list of categorical variables 
categorical_variables = ["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT", "SPECIAL_CONSIDERATIONS"]

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [10]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [11]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [12]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns=enc.get_feature_names())

# Review the DataFrame
encoded_df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,x0_T10,x0_T12,x0_T13,x0_T14,x0_T15,x0_T17,x0_T19,x0_T2,x0_T25,x0_T29,...,x5_1-9999,x5_10000-24999,x5_100000-499999,x5_10M-50M,x5_1M-5M,x5_25000-99999,x5_50M+,x5_5M-10M,x6_N,x6_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [13]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df, applicant_data_df.drop(columns=categorical_variables)], axis=1)

# Review the Dataframe
encoded_df

,x0_T10,x0_T12,x0_T13,x0_T14,x0_T15,x0_T17,x0_T19,x0_T2,x0_T25,x0_T29,...,x5_10M-50M,x5_1M-5M,x5_25000-99999,x5_50M+,x5_5M-10M,x6_N,x6_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [14]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df.IS_SUCCESSFUL

# Display a sample of y
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [15]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X

,x0_T10,x0_T12,x0_T13,x0_T14,x0_T15,x0_T17,x0_T19,x0_T2,x0_T25,x0_T29,...,x5_100000-499999,x5_10M-50M,x5_1M-5M,x5_25000-99999,x5_50M+,x5_5M-10M,x6_N,x6_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,36500179

### Step 6: Split the features and target sets into training and testing datasets.

In [16]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [17]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [63]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [19]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [20]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  32

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

32

In [21]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  8

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

8

In [22]:
# Create the Sequential model instance
model_neuron = Sequential()

In [23]:
# Add the first hidden layer
model_neuron.add(Dense(units = hidden_nodes_layer1, input_dim = number_input_features, activation = "relu"))

In [24]:
# Add the second hidden layer
model_neuron.add(Dense(units=hidden_nodes_layer2, input_dim = hidden_nodes_layer1, activation = "relu"))

In [25]:
# Add the output layer to the model specifying the number of output neurons and activation function
model_neuron.add(Dense(units=number_output_neurons, input_dim = hidden_nodes_layer2, activation = "sigmoid"))

In [26]:
# Display the Sequential model summary
model_neuron.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 32)                3744

 dense_1 (Dense)             (None, 8)                 264

 dense_2 (Dense)             (None, 1)                 9

=================================================================
Total params: 4,017
Trainable params: 4,017
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [27]:
# Compile the Sequential model
model_neuron.compile(loss="binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [28]:
# Fit the model using 50 epochs and the training data
model_neuron.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5813 - accuracy: 0.7141
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5534 - accuracy: 0.7287
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7311
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7321
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7325
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7339
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7331
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7340
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7348
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7352
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7355
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7355
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7366
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7352
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7366
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7364
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7356
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7364
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7367
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7361
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7361
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7367
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7377
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7368
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7376
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7376
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7387
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7386
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7374
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7373
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7383
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7375
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7385
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7388
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7378
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7382
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7389
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7385
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7384
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7390
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7388
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7397
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7385
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7389
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7379
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7386

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [29]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = model_neuron.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 [==============================] - 1s 1ms/step - loss: 0.5524 - accuracy: 0.7291
Loss: 0.5523620843887329, Accuracy: 0.7290962338447571

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [30]:
# Set the model's file path
file_path = "AlphabetSoup.h5"

# Export your model to a HDF5 file
model_neuron.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [31]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [32]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [33]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 116

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

116

In [34]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [36]:
# First hidden layer
nn_A1.add(Dense(units = hidden_nodes_layer1, input_dim = number_input_features, activation = "relu"))


# Output layer
nn_A1.add(Dense(units=number_output_neurons, input_dim = hidden_nodes_layer1_A1, activation = "sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 32)                3744

 dense_4 (Dense)             (None, 32)                1056

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 4,833
Trainable params: 4,833
Non-trainable params: 0
_________________________________________________________________

In [37]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [39]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5833 - accuracy: 0.7151
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5546 - accuracy: 0.7296
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7306
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7322
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7323
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7317
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7332
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7330
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7339
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7340
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7350
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7343
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7364
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7346
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7345
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7372
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7361
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7360
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7367
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7376
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7372
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7365
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7372
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7382
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7383
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7375
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7390
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7385
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7379
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7379
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7389
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7384
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7386
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7400
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7400
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7389
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7399
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7395
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7388
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7398
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7395
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7401
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7402
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7397
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7403
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7397
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7407

#### Alternative Model 2

In [40]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [41]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [53]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 64

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

64

In [54]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [55]:
# First hidden layer
nn_A2.add(Dense(units = hidden_nodes_layer1_A2, input_dim = number_input_features, activation = "relu"))


# Output layer
nn_A2.add(Dense(units=number_output_neurons, input_dim = hidden_nodes_layer1_A2, activation = "sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 64)                7488

 dense_13 (Dense)            (None, 1)                 65

=================================================================
Total params: 7,553
Trainable params: 7,553
Non-trainable params: 0
_________________________________________________________________

In [56]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [57]:
# Fit the model
nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5854 - accuracy: 0.7138
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7298
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5556 - accuracy: 0.7289
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5520 - accuracy: 0.7299
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5503 - accuracy: 0.7305
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7313
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7325
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7322
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7312
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7318
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7322
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7334
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7333
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7325
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7331
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7329
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7340
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7346
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7339
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7345
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7339
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7349
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7338
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7343
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7349
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7347
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7353
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7341
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7349
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7349
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7348
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7349
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7351
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7351
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7351
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7361
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7367
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7349
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7359
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7371
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7352
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7371
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7364
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7365
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7352
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7371
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7360
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7358
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7366
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7360

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [58]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = model_neuron.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 [==============================] - 1s 3ms/step - loss: 0.5524 - accuracy: 0.7291
Loss: 0.5523620843887329, Accuracy: 0.7290962338447571

In [59]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 [==============================] - 1s 3ms/step - loss: 0.5546 - accuracy: 0.7311
Loss: 0.5546448230743408, Accuracy: 0.7310787439346313

In [60]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 [==============================] - 1s 2ms/step - loss: 0.5557 - accuracy: 0.7308
Loss: 0.555695652961731, Accuracy: 0.7308454513549805

### Step 3: Save each of your alternative models as an HDF5 file.

In [61]:
# Set the file path for the first alternative model
file_path = "alt1_AlphabetSoup.h5"

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [62]:
# Set the file path for the second alternative model
file_path = "alt1_AlphabetSoup.h5"

# Export your model to a HDF5 file
nn_A2.save(file_path)